### ISSUE TITLE
SIL NRSI font versioning recommondation

### ISSUE THREAD

**Issue by khaledhosny** [openfv/openfv#9]
I have no much interest in font versioning schemes, but I just came across this document and I’m not sure if others are ware of, so I thought I’d point to it:
http://silnrsi.github.io/FDBP/en-US/Versioning.html

**Comment by khaledhosny** [comment]
Mentioned in https://github.com/openfv/openfv/issues/3#issuecomment-354921978 already.

**Comment by chrissimpkins** [comment]
@khaledhosny No worries Khaled.  @moyogo pointed this out to me yesterday.  I wasn't aware of this document.  Are there elements of the approach there that you feel would be appropriate to implement as part of a formal specification?  That document appears to be formatted as a best practices document rather than a formal spec.  It would be helpful to include what are considered best practices out there in the conversation so that this reflects those best practices across all stakeholders in the version string.
